// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALpQ_5x-ru3FTuQQVHsUPrQsfxv7QQIB4',
    appId: '1:923615600856:web:04e4ed555846cc51be37ad',
    messagingSenderId: '923615600856',
    projectId: 'sewingmobile',
    authDomain: 'sewingmobile.firebaseapp.com',
    databaseURL: 'https://sewingmobile-default-rtdb.firebaseio.com',
    storageBucket: 'sewingmobile.firebasestorage.app',
    measurementId: 'G-LMKCZZSSMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV1Ehz2ZvfQPS-yHlApFdKvg4HtdK_3sg',
    appId: '1:923615600856:android:8e99236dd11d8b31be37ad',
    messagingSenderId: '923615600856',
    projectId: 'sewingmobile',
    databaseURL: 'https://sewingmobile-default-rtdb.firebaseio.com',
    storageBucket: 'sewingmobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFFtEwrgMsd9wr6mdy3lB7IcuhtrCyjTg',
    appId: '1:923615600856:ios:a7caa4f02fe267d0be37ad',
    messagingSenderId: '923615600856',
    projectId: 'sewingmobile',
    databaseURL: 'https://sewingmobile-default-rtdb.firebaseio.com',
    storageBucket: 'sewingmobile.firebasestorage.app',
    iosBundleId: 'com.example.sewing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFFtEwrgMsd9wr6mdy3lB7IcuhtrCyjTg',
    appId: '1:923615600856:ios:a7caa4f02fe267d0be37ad',
    messagingSenderId: '923615600856',
    projectId: 'sewingmobile',
    databaseURL: 'https://sewingmobile-default-rtdb.firebaseio.com',
    storageBucket: 'sewingmobile.firebasestorage.app',
    iosBundleId: 'com.example.sewing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALpQ_5x-ru3FTuQQVHsUPrQsfxv7QQIB4',
    appId: '1:923615600856:web:7a0fca8c985729ffbe37ad',
    messagingSenderId: '923615600856',
    projectId: 'sewingmobile',
    authDomain: 'sewingmobile.firebaseapp.com',
    databaseURL: 'https://sewingmobile-default-rtdb.firebaseio.com',
    storageBucket: 'sewingmobile.firebasestorage.app',
    measurementId: 'G-2XLNF23LQL',
  );
}
